### ISSUE TITLE
[Glossary] Phrase that needn't be translated to Chinese.

### ISSUE THREAD

**Issue by xiaoya-Esther** [chaoss/translations#8]
This is the glossary for those  phrases that needn't be translated, any suggestions could be brought up in the comment, I will add them to the list below, in'()' are the translated phrases in the current version: 
- issue （问题）
- PR
- repo
- CHAOSS
- bug （错误）

**Comment by king-gao** [comment]
Hi,Xiaoya:

I Add some more proper noun.


  *   issue
  *   PR
  *   repo
  *   CHAOSS
  *   SPDX
  *   OPENCHAIN
  *   Linux
  *   Meetup
  *   License
  *   Github
  *   Gitlab
  *   Gitee
  *   Committer
  *   KPI
  *   Augur
  *   Grimoirelab
  *   GSOC
  *   GSOD


高琨/（King Gao）
2012实验室
2012Labs
[Company_logo]
华为技术有限公司 Huawei Technologies Co., Ltd.
Mobile: 15986646117
Email: ***@***.******@***.***>
地址：深圳市龙岗区坂田华为基地 邮编：518129
Huawei Technologies Co., Ltd.
Bantian, Longgang District,Shenzhen 518129, P.R.China

发件人: Xiaoya ***@***.***
发送时间: 2021年3月25日 18:34
收件人: chaoss/translations ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chaoss/translations] [Glossary] Phrase that needn't to be translated to Chinese. (#8)


This is the glossary for those phrases that needn't be translated, any suggestions could be brought up in the comment, I will add them to the list below:

  *   issue
  *   PR
  *   repo
  *   CHAOSS

**Comment by robekeane** [comment]
The word _issue_ is a common word in English, so we should take different actions in different cases, I think when _issue_ means "gitee/github issue" then it can be ommited, but when it means "问题/话题" it can be translated. You can find a lot of cases used in Chaoss Metrics that _issue_ is just a common word.

And _License_ is kind of issue of translation, because in Copyright Law of the People's Republic of China, the _License_ has its Chinese Term - 许可 . Comparing these use cases in Open Source, its a frequently used word, so I think _License_ can be translated to "许可/许可证"

**Comment by eyehwan** [comment]
Issue in [Github APIs Chinese references](https://docs.github.com/cn/rest/reference/issues) has given a reasonable(in my mind) word "议题"， which I prefer also. 
What do you think?

Also I create an [English-Chinese Comparison table](https://github.com/chaoss/translations/pull/23/files#diff-da847db859b3e92c9cdf056a44e655ace9a9a3b11d8ce028a0a74be4975d21dc) , we could add our proposal there.

**Comment by xiaoya-Esther** [comment]
Thanks! I think "Issue" as "议题" is reasonable whether to refer GitHub/Gitee Issue or common issues.
